![](https://cdn.shopify.com/s/files/1/0053/6513/7472/products/newyorkcitysunset911.jpg?v=1544036357)
([Image Source](https://gettyphotography.com/products/new-york-city-empire-state-building-sunset-911))

# Table of Contents

[1. Acknowledgement](#1)<br>
&nbsp;&nbsp;&nbsp;[Introduction](#1.1)<br>
[2. Import Library](#2)<br>
[3. Data Cleaning](#3)<br>
[4. Exploratory Data Analysis (EDA)](#4)<br>
&nbsp;&nbsp;&nbsp;[Extend the Summary Data](#4.1)<br>
[5. Hypothesis](#5)<br>
[6. Conclusion](#6)<br>
[7. Summary](#7)<br>

# Ackowlegement<a id='1'></a>
This Notebook would not have been possible without the fantastic dataset provided by [Kaggle](https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data). Also, shoutout to TKH volunteers: [Michael](https://www.linkedin.com/in/michael-lieberman-65786ba/), [Saurabh](https://www.linkedin.com/in/sauragar/) and our Instructors: Anil and [Malcolm](https://www.linkedin.com/in/malcolm-holliday/) who helped us with this project.


The $52 rental with a $125 cleaning fee
On Sept. 14, a Twitter user wrote, “Found a cheap @Airbnb for 52 dollars. Cleaning fee for 1 night, 125. Nonsense.”

It’s a typical complaint about the platform, which lists attractive nightly rates, but buries the fees until users begin booking. Cleaning and service fees can be modest — zero to $25, say — or add $450 to a booking, reflecting a mix of mandatory and optional host-applied fees. Sometimes there are additional occupancy taxes. And in some countries, Airbnb applies a Value Added Tax on its service fees.

Under Airbnb’s pricing structure, hosts pay the company 3 percent of the booking subtotal, which includes the nightly rate plus any cleaning fee and fees for additional guests. Most guests are charged a service fee of less than 14.2 percent of the booking subtotal, which goes to Airbnb. (If hosts elect to cover the fee entirely, they normally pay Airbnb 14 to 16 percent of the subtotal.)

Continue reading the main story
Because of their variability and lack of transparency, fees are the latest financial facet users have fixated on after the company created its extenuating circumstances policy during the pandemic. It said that travelers who had reservations made on or before March 14 could cancel and not be subject to cancellation fees, even if, in their rental agreement, they were in the penalty period. The policy has been extended several times, now to Oct. 31. (While most guests were happy with the resolution, many hosts were not and Airbnb later apologized to hosts for not consulting them).

Airbnb said it aims to introduce a redesign of price displays this year. “We’re trying to partner with hosts to create clear standards and change the search line, so if someone has higher cleaning fees, that affects their placement” in search results, Mr. Chesky said. “We’ve heard from travelers that they want a simpler way for us to show more of the price up front.”

Reckoning with racial bias
Four years before George Floyd was killed by police in Minneapolis, igniting this summer’s protests for social justice, the emergence of the hashtag #AirbnbWhileBlack called attention to a spate of racist incidents that users said happened at rental homes. Some Black renters were reported by neighbors as thieves. Others were subject to abuse by racist hosts rejecting their bookings. Complaints by Muslim, transgender and other groups followed.

Airbnb worked to purge discrimination from its platform by hiding guest’s profile pictures until a booking is confirmed; hiring anti-discrimination specialists to audit the platform; and creating a reporting channel to identify listings not complying with its nondiscrimination policy. The company said it has removed 1.3 million offenders.

This month, Airbnb plans to launch Project Lighthouse, a research initiative in the United States that aims to measure bias through perception based on names and photos, to determine where and when bias happens on the platform, from booking through reviews.

According to the company, the study has been in the works for two years in partnership with the racial justice organization Color of Change, with input from several social justice nonprofits, including Asian Americans Advancing Justice and the National Association for the Advancement of Colored People.

“It’s really hard to change what you can’t measure,” Mr. Chesky said. “Then hopefully we will use this data to continue to evolve our platform and reduce the bias.”

[source](https://www.nytimes.com/2020/09/24/travel/airbnb-pandemic.html)

# Introduction<a id='1.1'></a>


The biggest player in the short-term rental market, with more than 7 million listings in over 220 countries, is Airbnb. Over the years, its rampant growth and lack of transparency have made it a target for everything from charges of fueling overtourism and turning formerly residential neighborhoods into tourist zones to enabling raucous parties despite complaints and virus-related restrictions on gatherings. 
After laying off a quarter of its work force in the spring, Airbnb jettisoned some new ventures, including forays into transportation and entertainment, and hunkered down to focus on its core strength, lodging, even as its valuation fell from a high of $31 billion to, recently, $18 billion, according to The Wall Street Journal.

Airbnb has touted privacy and guests’ control over their environment — including having your own kitchen in lieu of patronizing restaurants — as safeguards during the pandemic. It instituted new cleaning guidelines and indicated in late August that more than 1 million listings had earned the “Enhanced Clean” certification, which involves training in new guidelines that detail how and what to wash and sanitize. The procedures recommend 45 minutes of cleaning per room. Some listings guarantee a 72-hour vacancy window before check in.[source](https://www.nytimes.com/2020/09/24/travel/airbnb-pandemic.html)

Venice and Florence demand a curb on Airbnb

A 90-day limit for Airbnbs
Urging the government to "take a hold of the situation in a serious, forward-looking way," they suggest classifying all rentals of under 30 days as for tourism purposes, and imposing a limit of two such rentals on owners per city, and a 90-day annual limit for rentals.
Many properties on Airbnb are owned by property investors who buy up handfuls of apartments to let in Italy's cities of art. They are often the cheapest, raising prices and squeezing locals out of the market.
Those who own more than two properties, or rent them for more than 90 days, should register as a business, suggest the mayors -- at which point they would be subject to that tax regime which is three times more punitive.
The cities are following in the footsteps of other overtouristed destinations including Paris, which allows people to rent out their primary residences for just 120 days a year; and Barcelona, which is mulling over a ban on short-term rentals.

[source](https://www.cnn.com/travel/article/venice-florence-airbnb-restrictions/index.html)

### The COVID effect
The coronavirus has taken a massive toll on the travel industry, which in turn has created a major challenge for Airbnb. 

During the fourth quarter of last year, Airbnb raked in $1.11 billion in revenue. But by the second quarter of this year, which covered the height of the pandemic, Airbnb’s revenue had dwindled to $334.78 million, down 72% year-over-year. The rising number of cancellations and slowing number of bookings ballooned Airbnb’s losses to $575.6 million in the second quarter, compared to a loss of $297.4 million during the same period one year prior. 

Last year, prior to suffering any effects from the pandemic, the company lost $674.33 million, far greater than its $16.9 million loss in 2018. Meanwhile, in the first nine months of 2020, the company has already lost $696.9 million, more than during all of 2019. [source](https://fortune.com/2020/11/16/airbnb-ipo-initial-public-offering-coronavirus-impact/)

## Technology Stack
In this analysis, we used python as the primary programming language because of its rich palette of tools that make data analysis a cinch. Some of the packages we used are:
1. [Matplotlib](https://matplotlib.org/) is an extremely versatile library of tools for generating interactive plots that are easy to interpret and customise.
2. [Numpy](https://github.com/numpy/numpy) is a popular library used for array manipulation and vector operations. It is used extensively across python projects that require scientific computing.
3. [Pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html) is another library for data science that is just as popular as numpy. It provides easy to use data structures and functions to manipulate structured data.
4. [Seaborn](https://seaborn.pydata.org/) is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics.
5. [Sqlite3](https://www.sqlite.org/index.html) is a C library that provides a lightweight disk-based database that allows accessing the database using a nonstandard variant of the SQL query language.
6. [Folium](https://python-visualization.github.io/folium/) makes it easy to visualize data that’s been manipulated in Python on an interactive leaflet map. It enables both the binding of data to a map for choropleth visualizations as well as passing rich vector/raster/HTML visualizations as markers on the map.

These tools are well documented and come with several examples that make it easy to start using them. You can check out the linked documentation pages for more information.

# Import Library<a id='2'></a>

In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3 as sql
# import folium
# from folium.plugins import HeatMap

In [5]:
db = 'project_2.db'
conn = sql.connect(db)

In [6]:
df = pd.read_sql("SELECT * from airbnb2017", conn, index_col='index')
df

,id,host_response_time,host_response_rate,host_is_superhost,host_has_profile_pic,neighbourhood_cleansed,latitude,longitude,is_location_exact,property_type,...,maximum_nights,calendar_updated,availability_30,number_of_reviews,review_scores_rating,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,reviews_per_month
index,,,,,,,,,,,,,,,,,,,,,
0,18461891,None,None,f,t,Ditmars Steinway,40.774142,-73.916246,t,Apartment,...,6,5 months ago,0,0,NaN,f,f,strict,f,NaN
1,20702398,within an hour,100%,f,t,City Island,40.849191,-73.786509,f,House,...,21,2 weeks ago,19,2,100.0,f,f,moderate,f,2.00
2,6627449,within an hour,100%,f,t,City Island,40.849775,-73.786609,t,Apartment,...,21,2 weeks ago,28,21,95.0,f,f,strict,f,0.77
3,19949243,within a few hours,100%,f,t,City Island,40.848838,-73.782276,f,Boat,...,1125,6 days ago,30,0,NaN,t,f,strict,f,NaN
4,1886820,None,None,f,t,City Island,40.841144,-73.783052,t,House,...,90,16 months ago,30,0,NaN,f,f,strict,f,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44312,20530309,within an hour,90%,f,t,Flatlands,40.618675,-73.932736,f,Apartment,...,1125,2 weeks ago,30,1,100.0,t,f,flexible,f,0.81
44313,20459907,within a few hours,100%,f,t,Bushwick,40.684681,-73.905174,t,Apartment,...,30,2 weeks ago,4,0,NaN,t,f,strict,f,NaN
44314,4287386,within an hour,100%,f,t,Rockaway Beach,40.583865,-73.819245,f,Apartment,...,60,2 weeks ago,1,6,87.0,f,f,moderate,f,3.91
44315,20939747,within an hour,100%,f,t,Rosedale,40.679998,-73.720787,f,Apartment,...,1125,a week ago,7,0,NaN,f,f,strict,f,NaN
44316,21135710,None,None,f,t,Upper West Side,40.776465,-73.970659,f,Apartment,...,1125,today,17,0,NaN,f,f,flexible,f,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44317 entries, 0 to 44316
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             44317 non-null  int64
 1   host_is_superhost              44317 non-null  object
 2   host_has_profile_pic           44317 non-null  object
 3   neighbourhood_cleansed         44317 non-null  object
 4   latitude                       44317 non-null  float64
 5   longitude                      44317 non-null  float64
 6   is_location_exact              44317 non-null  object
 7   property_type                  44317 non-null  object
 8   room_type                      44317 non-null  object
 9   accommodates                   44317 non-null  int64
 10  bathrooms                      44317 non-null  float64
 11  bedrooms                       44317 non-null  float64
 12  beds                           44317 non-null  float64
 13  bed_type                       44317 non-null  object
 14  amenities                      44317 non-null  object
 15  price                          44317 non-null  int64
 16  guests_included                44317 non-null  int64
 17  minimum_nights                 44317 non-null  int64
 18  maximum_nights                 44317 non-null  int64
 19  calendar_updated               44317 non-null  object
 20  availability_30                44317 non-null  int64
 21  number_of_reviews              44317 non-null  int64
 22  review_scores_rating           44317 non-null  float64
 23  instant_bookable               44317 non-null  object
 24  is_business_travel_ready       44317 non-null  object
 25  cancellation_policy            44317 non-null  object
 26  require_guest_profile_picture  44317 non-null  object
 27  reviews_per_month              44317 non-null  float64
 28  borough                        44317 non-null  object
 29  wifi_access                    44317 non-null  object
dtypes: float64(7), int64(8), object(15)
memory usage: 10.5+ MB

In [58]:
df2 = pd.read_sql("SELECT * from opennyc", conn, index_col='index')

In [61]:
info = df2.groupby(["neighbourhood","neighbourhood_group"])

In [62]:
pd.DataFrame(info)[0]

0                   (Allerton, Bronx)
1      (Arden Heights, Staten Island)
2           (Arrochar, Staten Island)
3                   (Arverne, Queens)
4                   (Astoria, Queens)
                    ...
216       (Windsor Terrace, Brooklyn)
217               (Woodhaven, Queens)
218                 (Woodlawn, Bronx)
219          (Woodrow, Staten Island)
220                (Woodside, Queens)
Name: 0, Length: 221, dtype: object

In [63]:
data= {key:value for key,value in pd.DataFrame(info)[0]}

In [64]:
data

{'Allerton': 'Bronx',
 'Arden Heights': 'Staten Island',
 'Arrochar': 'Staten Island',
 'Arverne': 'Queens',
 'Astoria': 'Queens',
 'Bath Beach': 'Brooklyn',
 'Battery Park City': 'Manhattan',
 'Bay Ridge': 'Brooklyn',
 'Bay Terrace': 'Queens',
 'Bay Terrace, Staten Island': 'Staten Island',
 'Baychester': 'Bronx',
 'Bayside': 'Queens',
 'Bayswater': 'Queens',
 'Bedford-Stuyvesant': 'Brooklyn',
 'Belle Harbor': 'Queens',
 'Bellerose': 'Queens',
 'Belmont': 'Bronx',
 'Bensonhurst': 'Brooklyn',
 'Bergen Beach': 'Brooklyn',
 'Boerum Hill': 'Brooklyn',
 'Borough Park': 'Brooklyn',
 'Breezy Point': 'Queens',
 'Briarwood': 'Queens',
 'Brighton Beach': 'Brooklyn',
 'Bronxdale': 'Bronx',
 'Brooklyn Heights': 'Brooklyn',
 'Brownsville': 'Brooklyn',
 "Bull's Head": 'Staten Island',
 'Bushwick': 'Brooklyn',
 'Cambria Heights': 'Queens',
 'Canarsie': 'Brooklyn',
 'Carroll Gardens': 'Brooklyn',
 'Castle Hill': 'Bronx',
 'Castleton Corners': 'Staten Island',
 'Chelsea': 'Manhattan',
 'Chinatown': 'Manhattan',
 'City Island': 'Bronx',
 'Civic Center': 'Manhattan',
 'Claremont Village': 'Bronx',
 'Clason Point': 'Bronx',
 'Clifton': 'Staten Island',
 'Clinton Hill': 'Brooklyn',
 'Co-op City': 'Bronx',
 'Cobble Hill': 'Brooklyn',
 'College Point': 'Queens',
 'Columbia St': 'Brooklyn',
 'Concord': 'Staten Island',
 'Concourse': 'Bronx',
 'Concourse Village': 'Bronx',
 'Coney Island': 'Brooklyn',
 'Corona': 'Queens',
 'Crown Heights': 'Brooklyn',
 'Cypress Hills': 'Brooklyn',
 'DUMBO': 'Brooklyn',
 'Ditmars Steinway': 'Queens',
 'Dongan Hills': 'Staten Island',
 'Douglaston': 'Queens',
 'Downtown Brooklyn': 'Brooklyn',
 'Dyker Heights': 'Brooklyn',
 'East Elmhurst': 'Queens',
 'East Flatbush': 'Brooklyn',
 'East Harlem': 'Manhattan',
 'East Morrisania': 'Bronx',
 'East New York': 'Brooklyn',
 'East Village': 'Manhattan',
 'Eastchester': 'Bronx',
 'Edenwald': 'Bronx',
 'Edgemere': 'Queens',
 'Elmhurst': 'Queens',
 'Eltingville': 'Staten Island',
 'Emerson Hill': 'Staten Island',
 'Far Rockaway': 'Queens',
 'Fieldston': 'Bronx',
 'Financial District': 'Manhattan',
 'Flatbush': 'Brooklyn',
 'Flatiron District': 'Manhattan',
 'Flatlands': 'Brooklyn',
 'Flushing': 'Queens',
 'Fordham': 'Bronx',
 'Forest Hills': 'Queens',
 'Fort Greene': 'Brooklyn',
 'Fort Hamilton': 'Brooklyn',
 'Fort Wadsworth': 'Staten Island',
 'Fresh Meadows': 'Queens',
 'Glendale': 'Queens',
 'Gowanus': 'Brooklyn',
 'Gramercy': 'Manhattan',
 'Graniteville': 'Staten Island',
 'Grant City': 'Staten Island',
 'Gravesend': 'Brooklyn',
 'Great Kills': 'Staten Island',
 'Greenpoint': 'Brooklyn',
 'Greenwich Village': 'Manhattan',
 'Grymes Hill': 'Staten Island',
 'Harlem': 'Manhattan',
 "Hell's Kitchen": 'Manhattan',
 'Highbridge': 'Bronx',
 'Hollis': 'Queens',
 'Holliswood': 'Queens',
 'Howard Beach': 'Queens',
 'Howland Hook': 'Staten Island',
 'Huguenot': 'Staten Island',
 'Hunts Point': 'Bronx',
 'Inwood': 'Manhattan',
 'Jackson Heights': 'Queens',
 'Jamaica': 'Queens',
 'Jamaica Estates': 'Queens',
 'Jamaica Hills': 'Queens',
 'Kensington': 'Brooklyn',
 'Kew Gardens': 'Queens',
 'Kew Gardens Hills': 'Queens',
 'Kingsbridge': 'Bronx',
 'Kips Bay': 'Manhattan',
 'Laurelton': 'Queens',
 'Lighthouse Hill': 'Staten Island',
 'Little Italy': 'Manhattan',
 'Little Neck': 'Queens',
 'Long Island City': 'Queens',
 'Longwood': 'Bronx',
 'Lower East Side': 'Manhattan',
 'Manhattan Beach': 'Brooklyn',
 'Marble Hill': 'Manhattan',
 'Mariners Harbor': 'Staten Island',
 'Maspeth': 'Queens',
 'Melrose': 'Bronx',
 'Middle Village': 'Queens',
 'Midland Beach': 'Staten Island',
 'Midtown': 'Manhattan',
 'Midwood': 'Brooklyn',
 'Mill Basin': 'Brooklyn',
 'Morningside Heights': 'Manhattan',
 'Morris Heights': 'Bronx',
 'Morris Park': 'Bronx',
 'Morrisania': 'Bronx',
 'Mott Haven': 'Bronx',
 'Mount Eden': 'Bronx',
 'Mount Hope': 'Bronx',
 'Murray Hill': 'Manhattan',
 'Navy Yard': 'Brooklyn',
 'Neponsit': 'Queens',
 'New Brighton': 'Staten Island',
 'New Dorp': 'Staten Island',
 'New Dorp Beach': 'Staten Island',
 'New Springville': 'Staten Island',
 'NoHo': 'Manhattan',
 'Nolita': 'Manhattan',
 'North Riverdale': 'Bronx',
 'Norwood': 'Bronx',
 'Oakwood': 'Staten Island',
 'Olinville': 'Bronx',
 'Ozone Park': 'Queens',
 'Park Slope': 'Brooklyn',
 'Parkchester': 'Bronx',
 'Pelham Bay': 'Bronx',
 'Pelham Gardens': 'Bronx',
 'Port Morris': 'Bronx',
 'Port Richmond': 'Staten Island',
 "Prince's Bay": 'Staten Island',
 'Prospect Heights': 'Brooklyn',
 'Prospect-Lefferts Gardens': 'Brooklyn',
 'Queens Village': 'Queens',
 'Randall Manor': 'Staten Island',
 'Red Hook': 'Brooklyn',
 'Rego Park': 'Queens',
 'Richmond Hill': 'Queens',
 'Richmondtown': 'Staten Island',
 'Ridgewood': 'Queens',
 'Riverdale': 'Bronx',
 'Rockaway Beach': 'Queens',
 'Roosevelt Island': 'Manhattan',
 'Rosebank': 'Staten Island',
 'Rosedale': 'Queens',
 'Rossville': 'Staten Island',
 'Schuylerville': 'Bronx',
 'Sea Gate': 'Brooklyn',
 'Sheepshead Bay': 'Brooklyn',
 'Shore Acres': 'Staten Island',
 'Silver Lake': 'Staten Island',
 'SoHo': 'Manhattan',
 'Soundview': 'Bronx',
 'South Beach': 'Staten Island',
 'South Ozone Park': 'Queens',
 'South Slope': 'Brooklyn',
 'Springfield Gardens': 'Queens',
 'Spuyten Duyvil': 'Bronx',
 'St. Albans': 'Queens',
 'St. George': 'Staten Island',
 'Stapleton': 'Staten Island',
 'Stuyvesant Town': 'Manhattan',
 'Sunnyside': 'Queens',
 'Sunset Park': 'Brooklyn',
 'Theater District': 'Manhattan',
 'Throgs Neck': 'Bronx',
 'Todt Hill': 'Staten Island',
 'Tompkinsville': 'Staten Island',
 'Tottenville': 'Staten Island',
 'Tremont': 'Bronx',
 'Tribeca': 'Manhattan',
 'Two Bridges': 'Manhattan',
 'Unionport': 'Bronx',
 'University Heights': 'Bronx',
 'Upper East Side': 'Manhattan',
 'Upper West Side': 'Manhattan',
 'Van Nest': 'Bronx',
 'Vinegar Hill': 'Brooklyn',
 'Wakefield': 'Bronx',
 'Washington Heights': 'Manhattan',
 'West Brighton': 'Staten Island',
 'West Farms': 'Bronx',
 'West Village': 'Manhattan',
 'Westchester Square': 'Bronx',
 'Westerleigh': 'Staten Island',
 'Whitestone': 'Queens',
 'Williamsbridge': 'Bronx',
 'Williamsburg': 'Brooklyn',
 'Willowbrook': 'Staten Island',
 'Windsor Terrace': 'Brooklyn',
 'Woodhaven': 'Queens',
 'Woodlawn': 'Bronx',
 'Woodrow': 'Staten Island',
 'Woodside': 'Queens'}

In [65]:
data['Gerritsen Beach']= 'Brooklyn'

In [66]:
data['Glen Oaks']= 'Queens'

In [67]:
data['Hollis Hills']= 'Queens'

In [68]:
df["borought"] = df["neighbourhood_cleansed"].apply(lambda x:data[x])

In [71]:
df

,id,host_is_superhost,host_has_profile_pic,neighbourhood_cleansed,latitude,longitude,is_location_exact,property_type,room_type,accommodates,...,calendar_updated,availability_30,number_of_reviews,review_scores_rating,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,reviews_per_month,borought
index,,,,,,,,,,,,,,,,,,,,,
0,18461891,f,t,Ditmars Steinway,40.774142,-73.916246,t,Apartment,Entire home/apt,2,...,5 months ago,0,0,0.0,f,f,strict,f,0.00,Queens
1,20702398,f,t,City Island,40.849191,-73.786509,f,House,Private room,2,...,2 weeks ago,19,2,100.0,f,f,moderate,f,2.00,Bronx
2,6627449,f,t,City Island,40.849775,-73.786609,t,Apartment,Entire home/apt,3,...,2 weeks ago,28,21,95.0,f,f,strict,f,0.77,Bronx
3,19949243,f,t,City Island,40.848838,-73.782276,f,Boat,Entire home/apt,4,...,6 days ago,30,0,0.0,t,f,strict,f,0.00,Bronx
4,1886820,f,t,City Island,40.841144,-73.783052,t,House,Entire home/apt,4,...,16 months ago,30,0,0.0,f,f,strict,f,0.00,Bronx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44312,20530309,f,t,Flatlands,40.618675,-73.932736,f,Apartment,Private room,1,...,2 weeks ago,30,1,100.0,t,f,flexible,f,0.81,Brooklyn
44313,20459907,f,t,Bushwick,40.684681,-73.905174,t,Apartment,Entire home/apt,6,...,2 weeks ago,4,0,0.0,t,f,strict,f,0.00,Brooklyn
44314,4287386,f,t,Rockaway Beach,40.583865,-73.819245,f,Apartment,Entire home/apt,4,...,2 weeks ago,1,6,87.0,f,f,moderate,f,3.91,Queens
44315,20939747,f,t,Rosedale,40.679998,-73.720787,f,Apartment,Entire home/apt,2,...,a week ago,7,0,0.0,f,f,strict,f,0.00,Queens
44316,21135710,f,t,Upper West Side,40.776465,-73.970659,f,Apartment,Entire home/apt,4,...,today,17,0,0.0,f,f,flexible,f,0.00,Manhattan

In [78]:
def wifi_locator(column):
    for row in df[column]:
        if "Wireless Internet" in row:
            return 1
        else:
            return 0
wifi_locator("amenities")

1

In [80]:
df["Wifi Access"] = df["amenities"].apply(lambda x: 1 if "Wireless Internet" in x else 0)

In [84]:
df["amenities"].iloc[44314]

'{"Wheelchair accessible",Kitchen,"Free parking on premises",Breakfast,Heating,"Smoke detector","Carbon monoxide detector",Essentials,Shampoo,Hangers,"Lake access",Beachfront}'

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44317 entries, 0 to 44316
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             44317 non-null  int64
 1   host_is_superhost              44317 non-null  object
 2   host_has_profile_pic           44317 non-null  object
 3   neighbourhood_cleansed         44317 non-null  object
 4   latitude                       44317 non-null  float64
 5   longitude                      44317 non-null  float64
 6   is_location_exact              44317 non-null  object
 7   property_type                  44317 non-null  object
 8   room_type                      44317 non-null  object
 9   accommodates                   44317 non-null  int64
 10  bathrooms                      44317 non-null  float64
 11  bedrooms                       44317 non-null  float64
 12  beds                           44317 non-null  float64
 13  bed_type                       44317 non-null  object
 14  amenities                      44317 non-null  object
 15  price                          44317 non-null  int64
 16  guests_included                44317 non-null  int64
 17  minimum_nights                 44317 non-null  int64
 18  maximum_nights                 44317 non-null  int64
 19  calendar_updated               44317 non-null  object
 20  availability_30                44317 non-null  int64
 21  number_of_reviews              44317 non-null  int64
 22  review_scores_rating           44317 non-null  float64
 23  instant_bookable               44317 non-null  object
 24  is_business_travel_ready       44317 non-null  object
 25  cancellation_policy            44317 non-null  object
 26  require_guest_profile_picture  44317 non-null  object
 27  reviews_per_month              44317 non-null  float64
 28  borought                       44317 non-null  object
 29  Wifi Access                    44317 non-null  int64
dtypes: float64(7), int64(9), object(14)
memory usage: 10.5+ MB

In [ ]:
# df.to_sql("updated_airbnb2017", conn, if_exists="replace")

# Data Cleaning<a id='3'></a>

The most important step to take before we get started geenrating any kind of information from all these data sources, it is first important to clean our data and make sure that the datasets are compatible with each other. Since most of the data is divided on a country-by-country basis, we must make sure that all the country names have the same formatting. 

For instance, "United States of America" may be written as "USA", "United Kingdom" as "UK" and so on. We will explore this problem and others in this section. We will prioritize only those countries for which vaccination data is available since most countries have either not yet started vaccinations or do not yet have sufficiently available public data.

# Exploratory Data Analysis (EDA)<a id='4'></a>

## Standardize Country Names

### Steps followed:
- Identify the differences 
- Plan on how to unify them 
- Implement in code

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.isna().sum()

In [ ]:
df.describe().T

In [ ]:
df.head()

In [ ]:
print('number of unique host: ', len(df['host_id'].unique()))
df['host_id'].value_counts()

In [ ]:
# number of neighbourhood groups
df['neighbourhood_group'].value_counts()

In [ ]:
fig, axes = plt.subplots(figsize=(10,10))
axes.set(title="Amount of BTC held by everyone other than Davin")
axes.pie(df['neighbourhood_group'].value_counts(), labels=df["neighbourhood_group"].unique(),explode=[0,0.05,0,0,0],autopct='%1.1f%%',shadow=True)
plt.legend()
plt.show()

In [ ]:
# number of different neighbourhood
len(df['neighbourhood'].unique())

In [ ]:
from matplotlib import style

plt.style.use('Solarize_Light2')
fig,ax=plt.subplots(figsize=(20,10))
color = ("blue", "red", "purple",'cadetblue','darksalmon')
df.neighbourhood.value_counts().sort_values(ascending=False)[:10].sort_values().plot(kind='barh',color=color)
ax.set_title("Top 10 neighbourhood by the number of listings available to book",size=24)
ax.set_xlabel('number of listings',size=15)
ax.set_ylabel('neighborhoods', size=15)
plt.show()

These are the 10 neighborhoods that have most listings, most rooms avaliable, apparently they are very popular.

In [ ]:
# number of room types
sns.countplot('room_type',data=df,order=df['room_type'].value_counts().index).set_title('Room Type')

This is a breakdown of the type of room/apt offered. As we can see these are mostly Entire Apartments or Private Rooms. There are very few Shared Rooms offered as an option for renting on AirBnb.

In [ ]:
plt.style.use('Solarize_Light2')
fig,ax=plt.subplots(figsize=(8,8))
df[['price']].boxplot()
plt.title('Price per night distribution')
#plt.xlabel('Days avaiable')
plt.ylabel('Cost per night') 
plt.show()

It seems that there are a few price outliers of $10000, let's see how many and what they are.

In [ ]:
df.sort_values(by=['price'], ascending=False).head(20)

#schoud we just drop row=9151?

In [ ]:
x = df['price'].values
y = df['neighbourhood_group'].values
plt.style.use('fivethirtyeight')
fig, ax = plt.subplots(figsize=(15,5))
ax.scatter(x,y, s=50, c='b', alpha=0.3)
ax.set_xlabel('price')
ax.set_ylabel('boroughs')
ax.set_title('Price distribution per neighborhood_group')
plt.show()

Also, let's drop last_review and reviews_per_month since they have lots of missing values (or better, lets fill the up with 0s since these are probably new properties.)

In [ ]:
#df.drop(['last_review', 'reviews_per_month'], axis = 1, inplace = True)
#or
# df.fillna(value = {'last_review':0}, inplace = True)
# df.fillna(value={'reviews_per_month':0}, inplace = True)

In [ ]:
plt.style.use('tableau-colorblind10')
fig, ax = plt.subplots(figsize=(15,5))
plt.hist(df['availability_365'], bins = 30)
plt.title('Avaliability')
plt.xlabel('Days avaiable')
plt.ylabel('Density') 
plt.show()

#most listings are avaliable short-term (more than 2 weeks)
fig, ax = plt.subplots(figsize=(15,5))
plt.hist(df[(df['minimum_nights'] <= 30) & (df['minimum_nights'] > 0)]['minimum_nights'], bins = 30)
plt.title('Minimum nights booking requiremnt')
plt.xlabel('Minimum of nights required to book')
plt.ylabel('Density')
plt.show()

# most books are for 1-2-3 days minimum
from matplotlib import colors
plt.style.use('tableau-colorblind10')
fig, ax = plt.subplots(figsize=(15,5))
plt.hist2d(df['number_of_reviews'],df['price'], bins=10, norm = colors.LogNorm(), cmap ="RdBu")
plt.title('Relationship between Number of Reviews and Price')
plt.xlabel('Number of reviews')
plt.ylabel('Price')
plt.show()

In [ ]:
#I will probably remove the last histogram - i wanted to do a 2d histogram, ut can't really find a good relationship for it. Ideas?

In [ ]:
sns.pairplot(df)

Aibnb Listing Distribution on a Heatmap

In [ ]:
data = folium.Map([40.7128,-74.0060],zoom_start=11)
HeatMap(df[['latitude','longitude']],radius=8,gradient={0.2:'blue',0.4:'purple',0.6:'orange',1.0:'red'}).add_to(data)
display(data)

The highest Density areas are marked in red and lowest density areas are marked in blue color

In [ ]:
plt.figure(figsize=(17,8))
plt.scatter(df.longitude, df.latitude, c=df.availability_365, cmap='plasma', edgecolor='black', linewidth=1, alpha=0.75)
cbar = plt.colorbar()
cbar.set_label('availability_365')
plt.title('Avaliability')
plt.show()

The Yellow color on the map shows the places which have more availability throughout the year, meaning that they are being rented throughout the whole year as opposed to on seasonal or weekly basis.

In [ ]:
#word cloud
from wordcloud import WordCloud, ImageColorGenerator
from PIL import Image
text = " ".join(str(each) for each in df.name)
# Create and generate a word cloud image:
wordcloud = WordCloud(width=800, height=400, margin=0,colormap='Blues').generate(text)
# Display the generated image:
plt.figure(figsize=(20,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()

In [ ]:
#this cloud be our banner at the end

# Extend the Summary Data <a id='4.1'></a>

The summary dataset already contains a lot of aggregate data about the virus itself but no information surrounding the vaccinations. So we will use the Vaccination dataset to add this information as new columns. This will make it significantly more convenient to process and visualize later on.

New Information:

- Number of vaccine doses administered
- Total number of unique people vaccinated 
- Total number of people fully vaccinated
- Number of vaccine doses administered per hundred
- Total number of unique people vaccinated per hundred
- Total number of people fully vaccinated per hundred 
- Vaccine combinations in use for each country
- Percentage of the total population vaccinated
- Percentage of the tested that returned positive


The numeric columns in the Vaccination dataset other than the ones marked "daily" are cumulative data. Hence the latest value will be the maximum among the column. For this reason, we will using the `groupby.max()` function as it works well with `NaN` values.

# Hypothesis <a id='5'></a>
#### What do we understand from this? 

We see that so far, the Pfizer Vaccine and BioNTech have been making the fastest growth, most likely since this is the one that is prominently being adminstered in the USA which as we saw, is leading in terms of daily vaccinations. We also see rapid growth for CNBG, Sinovac, the prominent combination from China. We hope that very soon, as vaccinations become more easily accessible and affordable, all line graphs see an upward trend, matching that of USA and China.

# Conclusion<a id='6'></a>

The above graphs shows how slowly but surely, the vaccines are being administered in increasingly large numbers each day. If we look carefully, we can also identify a slight downward trend in the number of new cases each day, as the vaccinations progress. Humanity is on its way to victory!

COVID-19 has taken a heavy toll on mankind. We have lost far too many people and suffered too much for too long. Now is the time to fight back. Let 2021 be the year we reclaim what 2020 took from us. Regardless of what people might say, always wear a mask when out in public and maintain social distancing. DO NOT give in hearsay! Only when all of the graphs plotted inthe innumerable notebooks posted by the talented people on Kaggle point heavily in our favour, having dwarfed the damage this pandemic has already done, will be be able to call it a victory. 

## TOGETHER, WE CAN!

# Summary<a id='7'></a>

Work Completed as of 05-02-2021: 

- **Data Cleaning** : Preprocessing and standardization.
- **Data Summarization** : Combine the daily vaccine information with the existing virus summary.
- **Summary Visualizations** : Generate attractive bar plots for various summaries.
- **Global Statistics Visualization** : Compare the daily new cases, active cases and deaths. 
- **Vaccine Preferences** : Visualize the vaccine combinations in use around the globe.
- **Covid-19 by Continents** : Visualize the total confirmed cases by continents.
- **Vaccination Progression** : Visualize clearly how the vaccination have been progressing across the globe. 
- **Rate of Vaccination by Country** : Visualise how each of the top-10 countries have been administering the vaccine
- **Vaccine vs Virus** : Comparing the global vaccination effort against the spread of the virus.
- **The Race Against Covid** : Comparing the cumulative numbers for the virus and the vaccine.
- **Vaccine Breakdown** : Visualizing how each vaccine has been administered over time.

Thanks for taking the time to read this notebook. If you liked it, an **UPVOTE** is massively encouraging! 
I will try to keep this notebook updated and add in more visualizations in the future so be sure to check back soon!